### ISSUE TITLE
Delete a service from Google Cloud Run

### ISSUE THREAD

**Issue by radufalcusanStoneone** [googleapis/google-api-java-client-services#10729]
- What you're trying to do: Removing a service or a revision from google Cloud Run
- What code you've already tried: 

![Screenshot 2021-11-03 at 17 16 40](https://user-images.githubusercontent.com/66017695/140099914-d3f82f5d-101d-4350-8a85-18512ec9b577.png)

- Any error messages you're getting: Illegalstateexception

- Important: The exception itself is not really important. What I would like to know is **how to delete a service or a revision from Google Cloud Run. Some code examples would really help me!**

**Comment by meltsufin** [comment]
I think you're looking for this: https://googleapis.dev/java/google-api-services-run/latest/com/google/api/services/run/v2/CloudRun.Projects.Locations.Services.Delete.html
