### ISSUE TITLE
TableSchema's set() method has not effect on getFields() result

### ISSUE THREAD

**Issue by slilichenko** [googleapis/google-api-java-client-services#10768]
When a schema needs to be created manually and `getFields()` is called later the approach of setting individual field one by one fails:

```new TableSchema()
            .set("request_ts", new TableFieldSchema()
                .setType("TIMESTAMP")
                .setMode("REQUIRED"));
```

because `getFields()` will return null. Clients must use `setFields()`:
```new TableSchema().setFields(
        List.of(
            new TableFieldSchema()
                .setName("request_ts")
                .setType("TIMESTAMP")
                .setMode("REQUIRED"))
```

At the very least the JavaDoc needs to explain this nuance.

**Comment by lesv** [comment]
@eaball35 Is this something you can do?

**Comment by suztomo** [comment]
Memo:

TableFieldSchema is at google-api-java-client-services/clients/google-api-services-bigquery/v2/2.0.0/com/google/api/services/bigquery/model/TableFieldSchema.java.

The Maven artifact that contains the class is:

```
    <dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-bigquery</artifactId>
      <version>v2-rev20220716-2.0.0</version>
    </dependency>
```

**Comment by suztomo** [comment]
@slilichenko Would you provide more code that generates the error, so that anyone can reproduce the issue?

**Comment by suztomo** [comment]
I'm closing this issue as part of our cleanup. Please reopen if this issue is still valid.
