### ISSUE TITLE
Versioning inconsistency

### ISSUE THREAD

**Issue by sukolenvo** [googleapis/google-api-java-client-services#12124]
Got a runtime exception `java.lang.ClassNotFoundException: com.google.api.client.json.jackson2.JacksonFactory` when using two google-api-service librarries that depend of different versions of `google-api-client`( `v1.33.1` with `v1.25.0`). 

Although `v1.32.1` seems to be working fine with `v1.33.1`, I find following confusing:
* `com.google.apis:google-api-services-secretmanager:v1-rev20211105-1.32.1` is using not `google-api-client:1.32.1`, but `v1.33.1` (commit https://github.com/googleapis/google-api-java-client-services/commit/ecfafdfa4b27dd23fa3872ae7ec41f5fc13189f8)
* There is no Gmail library that dependes on the same version `google-api-client:1.33.1`. Latest `com.google.apis:google-api-services-gmail:v1-rev20211108-1.32.1` version is still using `v1.32.1`.

**Comment by meltsufin** [comment]
Obsolete.
