### ISSUE TITLE
google-api-services-playcustomapp - Error apkNotificationMessageKeySignedWithShortKey

### ISSUE THREAD

**Issue by matButez** [googleapis/google-api-java-client-services#13158]
Hello,
Is there any way to get the reason of this error : apkNotificationMessageKeySignedWithShortKey return by [google-api-services-playcustomapp](https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-playcustomapp) ?

I don't find any information related to this error and i already used successfully this api few months ago with the same service account, same project id and google developper account.

```
PUT https://playcustomapp.googleapis.com/upload/playcustomapp/v1/accounts/*************/customApps?uploadType=resumable&upload_id=*****************

{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "apkNotificationMessageKeySignedWithShortKey",
    "reason" : "forbidden"
  } ],
  "message" : "apkNotificationMessageKeySignedWithShortKey",
  "status" : "PERMISSION_DENIED"
}
```

**Comment by diegomarquezp** [comment]
Hi @matButez. 
This error occurs when an APK has been signed with an insecure key size - RSA keys should have at least 2048 bits.
Please consider reaching out to our [Customer Support Hub](https://cloud.google.com/support-hub) for faster response times if you have a contract.
I'm closing this issue as it has been answered (`type: question`).
