### ISSUE TITLE
Why the number of nodes parameter is not returned as part of the response while using java client library to list the nodepools in a cluster

### ISSUE THREAD

**Issue by ragul-03** [googleapis/google-api-java-client-services#13207]
Hi all,
I'm trying to use the java client library (Container.Projects.Locations.Clusters.NodePools.List request) to list down the nodepools present in the cluster.
But, the response does not have the total number of nodes present in that nodepool. Is there any specific reason why it is not returned and is there any other way to get the total number of nodes present in that nodepool.

**Comment by meltsufin** [comment]
The response contains a `List<NodePool>`. Have you tried calling `size()` on it? I think that should give the correct count.
https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-container/v1/2.0.0/com/google/api/services/container/model/ListNodePoolsResponse.java#L38

**Comment by suztomo** [comment]
Closing this for obsolete. 

@ragul-03 Please check Mike's answer and if you still have problem, please reopen this or recreate an issue.
