### ISSUE TITLE
Issue with google-api-client 2.0.0 (originally YouTube Client)

### ISSUE THREAD

**Issue by DxsSucuk** [googleapis/google-api-java-client-services#13338]
I am trying to create YouTube instance which does not work since there is a internal check if the major version is more then one or not.
This check is keeps us from creating a YouTube instance, which would work without the check since the 2.0.0 release of the Google-Client-API did not have any breaking changes for the YouTube Library.

**Comment by paulmiddelkoop** [comment]
Same issue here with Google Sheets API. Temp fixed by using the previous version of the Google Client API: `com.google.api-client:google-api-client:1.35.2`.

**Comment by suztomo** [comment]
There's a bug in version confirming logic. Please use the google-api-client version declared by the library.

**Comment by suztomo** [comment]
Update: We fixed the logic of version checking. We have released some of the libraries with version suffix "-2.0.0". E.g., 
[com.google.apis:google-api-services-bigquery:v2-rev20220730-2.0.0](https://search.maven.org/artifact/com.google.apis/google-api-services-bigquery/v2-rev20220730-2.0.0/jar). Youtube client should be available soon.

**Comment by DxsSucuk** [comment]
Thanks!
Tested it with the newest version and everything works now!
