### ISSUE TITLE
Confusing message

### ISSUE THREAD

**Issue by alamothe** [googleapis/google-api-java-client-services#13824]
```
You are currently running with version 2.0.0 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.32.1 of the Cloud SQL Admin API library.
```

#### Environment details

  - Programming language: Java

#### Steps to reproduce

  1. 
```
	api("com.google.cloud.sql:mysql-socket-factory-connector-j-8:1.6.3")
	api("com.google.cloud.sql:postgres-socket-factory:1.6.3")
	api("com.google.api-client:google-api-client:2.0.0")

```

**Comment by ctasada** [comment]
The message is generated at https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-sqladmin/v1beta4/1.30.1/com/google/api/services/sqladmin/SQLAdmin.java#L44 

The code doesn't seem to take in consideration major upgrades.

**Comment by suztomo** [comment]
We have released some of the libraries with version suffix "-2.0.0". E.g.,
[com.google.apis:google-api-services-bigquery:v2-rev20220730-2.0.0](https://search.maven.org/artifact/com.google.apis/google-api-services-bigquery/v2-rev20220730-2.0.0/jar). Please use that versions.
