### ISSUE TITLE
google home graph request sync working only locally

### ISSUE THREAD

**Issue by OtavioSDev** [googleapis/google-api-java-client-services#14182]
I'm trying to do a requestSync, it works locally but on the server (aws lambda) it returns 400 and the message "Request contains an invalid argument."

the body and header of the request are the same, I see no reason to work in one environment and not in another.

Is there any configuration in the HomeGraph Api console to accept requests from any domain?

**Comment by diegomarquezp** [comment]
Hi @OtavioSDev, are you still running into this issue? If so, can you please share a reproducer?

**Comment by diegomarquezp** [comment]
Hi @OtavioSDev, I'll be closing this issue in the meantime due to lack of activity. Please feel free to reopen it if needed.
