### ISSUE TITLE
Updating Sheets to use google-api-client.version 2.0.0?

### ISSUE THREAD

**Issue by drew-at-platonicideal** [googleapis/google-api-java-client-services#14513]
I'm updating a project to use the current version of Google Api Client (2.0.0), which Sheets rejects in the precondition version check. 

`  static {

    com.google.api.client.util.Preconditions.checkState(

        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&

        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,

        "You are currently running with version %s of google-api-client. " +

        "You need at least version 1.15 of google-api-client to run version " +

        "1.18.0-rc of the Google Sheets API library.", com.google.api.client.googleapis.GoogleUtils.VERSION);

  }`

When will Sheets be updated?

**Comment by meltsufin** [comment]
Can you provide a reproducable example? What does your POM look like?

**Comment by suztomo** [comment]
The libraries should now depend on google-api-client version > 2.0.0 by now.
