### ISSUE TITLE
gmail.users().history() return FAILED_PRECONDITION error

### ISSUE THREAD

**Issue by roma2341** [googleapis/google-api-java-client-services#15307]
#### Environment details

  - Programming language:
  - OS: Windows 10
  - Language runtime version: java 15.0.2
  - Package version: google-api-services-gmail v1-rev20221219-2.0.0

#### Steps to reproduce
  Initially i fetch list of accounts on my workspace account: i have ~ 1500 accounts. Then i watch gmail messages changes using gcloud pub/sub. When i receive historyId i use it to fetch historyList for user and everything works fine, but i got strange error after 10-15 calls of gmail.users().history().list() :
```
  {
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "message": "Precondition check failed.",
      "reason": "failedPrecondition"
    }
  ],
  "message": "Precondition check failed.",
  "status": "FAILED_PRECONDITION"
}
```

    Here is my code excerpt:

```
protected List<String> ACCESS_SCOPES = List.of(DirectoryScopes.ADMIN_DIRECTORY_USER,
            "https://www.googleapis.com/auth/pubsub",
            "https://mail.google.com");
     GoogleCredentials credentials = GoogleCredentials.fromStream(new ClassPathResource("google-credentials.json")
                .getInputStream()).createScoped(ACCESS_SCOPES);
  var delegatedCredentials = credentials.createDelegated(emailAddress);
                    delegatedCredentials.refreshIfExpired();
                    Gmail gmail = gloggerGmailService.getService(delegatedCredentials);
  ListHistoryResponse historyResponse = gmail.users().history().list("some_email_of_workspace_user")
                    .setStartHistoryId(startHistoryId)
                    .setPageToken(nextPageToken)
                    .setHistoryTypes(List.of("messageAdded"))
                    .execute();
```

It's very strange, because it fails even for gmail accounts what gave successfull response previously (first 10-15 calls or previous strartups). I don't know what is wrong, becuase google don't return normal error only mystic FAILED_PRECONDITION, how i can solve this problem ? Maybe i exceed some quota or rate limit ? But shouldn't the library itself include rate limiting logic ? I very disappointed because i had this error - FAILED_PRECONDITION previously - every week or two our application had to be restarted or this FAILED_PRECONDITION error appears constantly on every gmail api call we use until we restarted application. We accepted this bug, because when i created issue on github nobody answered me, but that issue wasn't so critical, because it appears only once a week, but now i can't synchonize my users mailboxes with our crm database, because after several requests google api stops working at all and returns FAILED_PRECONDITION.

**Comment by roma2341** [comment]
I found the reason.
I use Spring framework. When i use my code at @PostConstruct everyting works fine.
When i use it at  @Scheduled(fixedDelay = 5000) it goes crazy(

**Comment by roma2341** [comment]
I have fixed my issue, but i don't understand why it works when i return new google credentials every time and doesn't work when i store credentials in my service. As i understand credentails are immutable, aren't they ?
Previous service version: 
```
@Service
public class GoogleAdminService {

    protected volatile GoogleCredentials credentials;

    protected List<String> ACCESS_SCOPES = List.of(DirectoryScopes.ADMIN_DIRECTORY_USER,
            "https://www.googleapis.com/auth/pubsub",
            "https://mail.google.com");

    public GoogleAdminService() throws IOException {
        credentials = GoogleCredentials.fromStream(new ClassPathResource("google-credentials.json")
                .getInputStream()).createScoped(ACCESS_SCOPES);
    }

    public GoogleCredentials getCredentials() {
       return credentials;
    }

    public GoogleCredentials getDelegatedCredentials(String email) {
        return credentials.createDelegated(email);
    }
}
```
Fixed service version:
```
@Service
public class GoogleAdminService {

    protected List<String> ACCESS_SCOPES = List.of(DirectoryScopes.ADMIN_DIRECTORY_USER,
            "https://www.googleapis.com/auth/pubsub",
            "https://mail.google.com");

    public GoogleCredentials getCredentials() {
        try {
            return GoogleCredentials.fromStream(new ClassPathResource("google-credentials.json")
                    .getInputStream()).createScoped(ACCESS_SCOPES);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
    public GoogleCredentials getDelegatedCredentials(String email) {
        return getCredentials().createDelegated(email);
    }
}
```

**Comment by meltsufin** [comment]
The error message is coming from the actual Gmail API. So, you might want to ask a question [there](https://developers.google.com/gmail/api/support). @TimurSadykov Do you have some insight on this? Does the user have to periodically refresh the credentials or something?

**Comment by TimurSadykov** [comment]
Hey, I agree it is something GMail specific. Would be interested to know the root cause as well.
