### ISSUE TITLE
How to import com.google.apis:google-api-services-apigee Maven package

### ISSUE THREAD

**Issue by alex-rocha-hp** [googleapis/google-api-java-client-services#15623]
I'm trying to use the Maven package com.google.apis:google-api-services-apigee, but I can't find it in the Maven Central Repo

I've followed the documentation for both version [1.31.0](https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-apigee/v1/1.31.0/README.md) and [2.0.0](https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-apigee/v1/2.0.0/README.md).

**Comment by meltsufin** [comment]
@suztomo @blakeli0 I can't find it either.

**Comment by suztomo** [comment]
Nothing in Maven Central https://search.maven.org/artifact/com.google.apis/google-api-services-apigee

Memo the readme is https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-apigee/v1/2.0.0.

**Comment by diegomarquezp** [comment]
Hi @alex-rocha-hp. Thanks for reporting this. Unfortunately, `google-api-services-apigee` is indeed unavailable, but we have two other libraries to allow interaction with apigee.

1. [apigee-connect](https://github.com/googleapis/google-cloud-java/tree/main/java-apigee-connect). Can be installed with
```
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-apigee-connect</artifactId>
  <version>2.8.0</version>
</dependency>
```
2. [apigee-registry](https://github.com/googleapis/google-cloud-java/tree/main/java-apigee-registry). Can be installed with 
```
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-apigee-registry</artifactId>
  <version>0.8.0</version>
</dependency>
```
