### ISSUE TITLE
Update README with latest version of google-api-services-cloudkms

### ISSUE THREAD

**Issue by roar-skinderviken** [googleapis/google-api-java-client-services#15685]
**Problem**
README for google-api-services-cloudkms points to a version different from latest:
https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-cloudkms/v1/README.md

Issue with older versions of google-api-services-cloudkms, is lack of supporting google-api-client:2.x, and you'll get an error like this:
```
You are currently running with version 2.2.0 of google-api-client. You need at least version 1.15 of google-api-client to run version <VERSION> of the Cloud Key Management Service (KMS) API library.
```

**Solution**
Please update README with latest version of google-api-services-cloudkms which is: v1-rev20221107-2.0.0.

In Maven Central, latest version appears in the middle of the version list, hence it is hard to find:
https://mvnrepository.com/artifact/com.google.apis/google-api-services-cloudkms

**Comment by suztomo** [comment]
I'll close this in favor of #16629
