### ISSUE TITLE
Clients have an outdated readme at the root of their api version folder

### ISSUE THREAD

**Issue by diegomarquezp** [googleapis/google-api-java-client-services#16629]
General case of https://github.com/googleapis/google-api-java-client-services/issues/15685 
For each api version (e.g. `v1`, `v2`, `v1alpha1`), there are several folders with versions of the generator used to produce the library (e.g. `1.31.0`, `2.0.0`).
Many api version folders have a stale README file
Examples:
* https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-abusiveexperiencereport/v1 
* https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-acceleratedmobilepageurl/v1

Suspected cause: a previous generator version was generating such README and then it stopped doing so, leaving the api versions folder with a stale README.

I propose simply removing readmes at this folder level, since there is a correct readme inside each generator version folder ([example](https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-acceleratedmobilepageurl/v1/2.0.0))

**Comment by lqiu96** [comment]
We are looking into this issue.

**Comment by lqiu96** [comment]
Looked at the logs of the previous PRs that updated the root README. It seems to have been done via the `synth.py` file: https://github.com/googleapis/google-api-java-client-services/blob/23cb5cb405d84d89db3b9e90f33b4ca6087d5180/synth.py

That file was deleted in early 2022 (seems to have been replaced with GH actions to generate the libraries): https://github.com/googleapis/google-api-java-client-services/pull/11481

The script seemed to have logic to copy over the README from the latest variant as the root README: https://github.com/googleapis/google-api-java-client-services/blob/8d0198de8bfee76631693a63477bb61013d55715/synth.py#L133-L137

One possible fix to append the current workflow generation GH action with a copy command to replicate this behavior:
i.e. something like:
```
  # copy the latest README to the main service location
  cp ${ROOT_DIR}/google-api-java-client-services/clients/google-api-services-${SERVICE}/${VERSION}/${LATEST_VARIANT}/README.md ${ROOT_DIR}/google-api-java-client-services/clients/google-api-services-${SERVICE}/${VERSION}/README.md
```

**Comment by lqiu96** [comment]
Another option is @diegomarquezp's suggestion of deleting the each service's root README. I think having the root README saves the user a click (having to click into the version and finding the README) and also allows us to suggest them to use the latest version (version from the latest variant).

**Comment by suztomo** [comment]
Having the latest version shown in the README of the service is user-friendly as they can find the recommended version easily.

**Comment by diegomarquezp** [comment]
I agree with @suztomo and @lqiu96 , although deleting the READMEs at the root folders is the easiest to implement it will be less convenient for the user in terms of navigation (i.e. figure out which generator version should they click on, for which we don't have a clear explanation).

@lqiu96 I think adding a copy step to bring the readme from `$LATEST_VERSION` into the version's root as you say should do fine
