### ISSUE TITLE
Java golden files are not tested anywhere in `generator/tests`

### ISSUE THREAD

**Issue by diegomarquezp** [googleapis/google-api-java-client-services#16707]
Golden java files, defined [generator/tests/testdata/golden/java/default](https://github.com/googleapis/google-api-java-client-services/tree/main/generator/tests/testdata/golden/java/default), were _probably_ added to confirm the generator produces java classes looking as these, but I could not find any part in the `generator/test` folder that mentions such golden java classes, although I could find mentions of *golden discovery files*. I also did a quick lookup at blame files in this folder, as well as inspecting the test classes looking for mentions of golden files/golden directory scan/etc.

We could write a java golden test from scratch, but it also could be that the import from google3 did not include such tests (if any).

**Comment by diegomarquezp** [comment]
Deprioritizing to p3 as this is planned for 2023 Q3

**Comment by suztomo** [comment]
The files were added https://github.com/googleapis/google-api-java-client-services/commit/8094658a0cc8d515484e8834d74e34b418653d95

**Comment by suztomo** [comment]
Even with the commit https://github.com/googleapis/google-api-java-client-services/commit/8094658a0cc8d515484e8834d74e34b418653d95, `.kokoro/generator_test.sh` succeeds. Note that I had to run `pyenv install 2.7.18 && pyenv local 2.7.18`. I'm going to delete the golden directory.
