### ISSUE TITLE
BigQuery: Invalid data key for `numTotalLogicalBytes` in `com.google.api.services.bigquery.model.Table`

### ISSUE THREAD

**Issue by sumeetgajjar** [googleapis/google-api-java-client-services#16915]
version: v2-rev20230408-2.0.0

### Description

The `numTotalLogicalBytes` field of `com.google.api.services.bigquery.model.Table` class has an incorrect `@Key` annotation.

In its current state the annotation value is `num_total_logical_bytes`. 
There's no need for the value in the `@Key("<placeholder value>")` annotation, just `@Key` is enough since the json field and the java field have the exact same name.

https://github.com/googleapis/google-api-java-client-services/blob/09b3ea51aac423a1529b459d82abd5db736d4ed9/clients/google-api-services-bigquery/v2/2.0.0/com/google/api/services/bigquery/model/Table.java#L260-L261

### How did we found the bug?

We recently filed the following PR https://github.com/googleapis/java-bigquery/pull/2673 that exposes the above field along with similar storage information in java-bigquery client.

The required integration tests failed for the above PR.

We attached a debugger to the failing integration test and deep dived into the code.

Further investigation surfaced that `com.google.api.services.bigquery.model.Table` which extends `com.google.api.client.json.GenericJson` has the above described bug in it.

Running the following snippet of the code where `tablePb` is an instance of `com.google.api.services.bigquery.model.Table` class returns inconsistent response where in-fact both stmts are trying to fetch the same logical information.

```java
tablePb.getNumTotalLogicalBytes() // shall return null
tablePb.get("numTotalLogicalBytes") // shall return a valid long value
```

This issue is present not only for `numTotalLogicalBytes` but also for the following fields

- `numActiveLogicalBytes`
- `numActivePhysicalBytes`
- `numLongTermLogicalBytes`
- `numLongTermPhysicalBytes`
- `numPartitions`
- `numTimeTravelPhysicalBytes`
- `numTotalLogicalBytes`
- `numTotalPhysicalBytes`

### Suggested Fix
- Remove the value from the `@Key` annotation for the above listed fields.

**Comment by sumeetgajjar** [comment]
cc: @diegomarquezp @emmileaf

**Comment by Neenu1995** [comment]
@sumeetgajjar , Thanks for looking into this. 
This is a known issue and we have team working on fixing this at the root.

**Comment by shollyman** [comment]
This should be addressed in the service definition, but will take a while to make it's way into the generated discovery library here.  Once the `discovery document` bears a revision past 20230504, the java library should use the correct fields in the response.

Internally, change 529497573

**Comment by sumeetgajjar** [comment]
Thanks @Neenu1995 @shollyman for the update,
will be on the lookout for the update in the discovery document.

**Comment by alicejli** [comment]
Closing as this should have been fixed. Please re-open if not.
