### ISSUE TITLE
SqlAdmin: user update failed due to Missing parameter: user. 

### ISSUE THREAD

**Issue by lturcsanyi** [googleapis/google-api-java-client-services#16951]
[https://github.com/googleapis/google-api-java-client-services/blob/61f99cd1ba6d506de77e04d8c10a75fbb4eedc8a/clients/google-api-services-sqladmin/v1/2.0.0/com/google/api/services/sqladmin/SQLAdmin.java#L8019](https://github.com/googleapis/google-api-java-client-services/blob/61f99cd1ba6d506de77e04d8c10a75fbb4eedc8a/clients/google-api-services-sqladmin/v1/2.0.0/com/google/api/services/sqladmin/SQLAdmin.java#L8019)

user query parameter is missing from users update REST_PATH template

[https://cloud.google.com/sql/docs/postgres/admin-api/rest/v1/users/update#query-parameters](https://cloud.google.com/sql/docs/postgres/admin-api/rest/v1/users/update#query-parameters)

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: -
3. Java version: -
4.  version(s): v1/2.0.0

#### Steps to reproduce

  1. Update user calling `sqlAdmin.users().update(projectId, instance, user).execute();`
    ```
    {
    "code" : 400,
    "errors" : [ {
      "domain" : "global",
      "message" : "Missing parameter: user.",
      "reason" : "required"
    } ],
    "message" : "Missing parameter: user."
    }
    ```

After adding ?user=<<user>> to the REST_PATH, it succeeds.

#### External references such as API reference guides

[https://cloud.google.com/sql/docs/postgres/admin-api/rest/v1/users/update#query-parameters](https://cloud.google.com/sql/docs/postgres/admin-api/rest/v1/users/update#query-parameters)

#### Any additional information below

Thanks!

**Comment by mpeddada1** [comment]
@lturcsanyi Thanks for creating this issue! Could you provide us with a reproducer or some more information about your application to help us better understand the problem you're experiencing?

**Comment by mpeddada1** [comment]
Thanks @lturcsanyi! Another follow-up, are you seeing this issue with v1/1.31.0 as well?

**Comment by lturcsanyi** [comment]
@mpeddada1 Yes

**Comment by diegomarquezp** [comment]
Following up on @mpeddada1 's investigation.

The discovery doc definition for this method contains a _non-required_ query parameter "name" that is _actually required by the server_

https://github.com/googleapis/discovery-artifact-manager/blob/master/discoveries/sqladmin.v1.json#L1492-L1536

If I add `required: true` to the discovery doc and perform a manual generation, then the client works correctly (see https://github.com/googleapis/google-api-java-client-services/pull/17304/files to find the expected changes)

Using @lturcsanyi 's reproducer as a start, and after confirming the bug, when I used this version of the library the call was successful. The final reproducer was:

```java
    static void testUsers() throws IOException {
        UsersListResponse usersListResponse = sqlAdmin.users().list(projectId, instanceName).execute();
        List<User> users = usersListResponse.getItems();
        System.out.println(users);
        User testUser = users.get(1);
        testUser.setHost(null);
        testUser.setPassword("test-password");
        SQLAdmin.Users.Update updateRequest = sqlAdmin.users().update(
          projectId, 
          instanceName, 
          /* REQUIRED BY LIBRARY GENERATED BY ALTERED DISCOVERY DOC */ 
          userName, 
          testUser);
        Operation operation = updateRequest.execute();
        System.out.println(operation);
    }

```

CC: @blakeli0

**Comment by alicejli** [comment]
@diegomarquezp Is there a documentation update that needs to happen?

**Comment by dazuma** [comment]
Just a note here: the "canonical" source for the discovery doc is https://sqladmin.googleapis.com/$discovery/rest?version=v1 and it matches the source we're generating from at https://github.com/googleapis/discovery-artifact-manager/blob/master/discoveries/sqladmin.v1.json. (Yes, the versions aren't exactly the same, but the actual content is semantically identical.) So any change needed to address this, whether to set the field to required, update the documentation, or anything else, needs to be done by the Cloud SQL service team in the canonical discovery documents they publish at https://sqladmin.googleapis.com/$discovery/rest?version=v1. After that happens, the code generation pipeline should update the SDK automatically.

**Comment by blakeli0** [comment]
@lturcsanyi As Daniel pointed out, this is not a client specific issue, we already reached out to the service for further assistance. In the mean time, if you need it to be fixed sooner and have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub, this will ensure a timely response.
