### ISSUE TITLE
Application name is not set. Call Builder#setApplicationName.

### ISSUE THREAD

**Issue by amormz** [googleapis/google-api-java-client-services#17332]
Use the localservice java sdk to pull report, but the following error occurs：
Application name is not set. Call Builder#setApplicationName.
I don't see a method for setting the application name, Thank you for your reply

```java
Localservices.AccountReports.Search search = localservices.accountReports().search();
// ...
GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse execute = search.execute();
```

version:v1-rev20220612-2.0.0

**Comment by meltsufin** [comment]
I see `Localservices.setApplicationName()`
https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-localservices/v1/2.0.0/com/google/api/services/localservices/v1/Localservices.java#L866

**Comment by amormz** [comment]
thank

**Comment by amormz** [comment]
> I see `Localservices.setApplicationName()`
> https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-localservices/v1/2.0.0/com/google/api/services/localservices/v1/Localservices.java#L866

thank
