### ISSUE TITLE
Google Chat Card UI Widgets: Button reappears after using UPDATE_MESSAGE to hide it

### ISSUE THREAD

**Issue by diaowenyang** [googleapis/google-api-java-client-services#17333]
I am encountering an issue while using the Button component of the Google Chat Card UI Widgets as a Java developer. After sending a Card to a user and including a Button within the Card, when the user clicks the Button, I use UPDATE_MESSAGE to hide the Button. However, after a certain period of time, the Card reverts back to its original state, and the Button reappears.

Expected Behavior: I expect that after using UPDATE_MESSAGE to hide the Button, the Card should retain its modified state and not automatically revert back to the initial state.

Steps to Reproduce:

Create a Card and add a Button component within the Card.
Send the Card to a user.
User clicks the Button.
Use UPDATE_MESSAGE to hide the Button.
Wait for some time and review the state of the Card again.
Actual Result: After a certain period of time, the Card reverts back to its original state, and the Button reappears.

This issue is crucial for me as I need to be able to dynamically update the content of the Card and have it persist in the modified state. I kindly request the Google team to address this issue and ensure that after using UPDATE_MESSAGE to hide the Button, the Card remains in the modified state persistently.

Version:
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-chat</artifactId>
            <version>v1-rev20230216-2.0.0</version>
        </dependency>

Thank you!

**Comment by meltsufin** [comment]
This repository doesn't contain any UI Widgets.
