### ISSUE TITLE
google-api-services-androidpublisher -> No consume API?

### ISSUE THREAD

**Issue by ubarua123** [googleapis/google-api-java-client-services#17540]
Thanks for stopping by to let us know something could be better!

**Is your feature request related to a problem? Please describe.**
I noticed there's an REST API to consume a Google Play Product however there is no api in the client library. [https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/consume](url)

**Describe the solution you'd like**
Inclusion of the consume product API in the client library

**Describe alternatives you've considered**
Right now it needs to be done on the app side i.,e Google Play Billing library however that's not reliable considering a user's network connection. Better if handled on the backend.

**Comment by lqiu96** [comment]
> I noticed there's an REST API to consume a Google Play Product however there is no api in the client library.

I think I'm missing something. What do you mean by there's a REST API to consume Google Play Product but no api in the Client Library. Can you point me to where you see the REST API to consume?

**Comment by burkedavison** [comment]
Closing issue due to lack of OP response. Please reopen if this is still an issue.
