### ISSUE TITLE
Java SDK SQL Admin : 404 Error after changed the service path. 

### ISSUE THREAD

**Issue by mssaravanan** [googleapis/google-api-java-client-services#17544]
I have created the Cloud SQL user using the **SQL Admin java SDK**, the user creeated successfully. Trying to **login with user failed**, It throws **password authendication failed**.

I have tried the same with console API, it works correctly.
https://cloud.google.com/sql/docs/postgres/admin-api/rest/v1beta4/users#http-request

The **sdk** used the 
**https://sqladmin.googleapis.com/v1/projects/{project-name}/instances/{instance-name}**

But in REST API 
https://content-sqladmin.googleapis.com/sql/v1beta4/projects/{project-name}//instances/{instance-name}/users?alt=json&key=key_value

So I have **changed service path** using below code, I got **404 Error** 

`new SQLAdmin.Builder(httpTransport, jsonFactory, requestInitializer)
                    .setServicePath("sql/v1beta4/")
                    .setApplicationName("Custom-UserManager/0.1")
                    .build();`
 
https://sqladmin.googleapis.com/sql/v1beta4/v1/projects/appranix-managed-dev-01/instances/postgres3/users

#### Environment details
1. Envronment: Cloud Function 
2. Dependency: com.google.apis:google-api-services-sqladmin:v1-rev20230607-2.0.0
3. Java version: Java 17 temurin

Thanks!

**Comment by mpeddada1** [comment]
@mssaravanan Thanks for filing this issue! Is it possible to provide a small reproducer for this problem? Additionally, are you seeing this with v1/1.31.0 as well?

**Comment by ddixit14** [comment]
Closing this as reproducer code not provided, will open it if the user still needs help.
