### ISSUE TITLE
Get progress of uploading file in bytes (Drive API v3)

### ISSUE THREAD

**Issue by vipulm7** [googleapis/google-api-java-client-services#17982]
(Drive API v3)

**What is feature request? Please describe.**
There is no function or listener that updates us with the amount of bytes uploaded.

**Describe the solution you'd like**
When uploading a file using google drive api, it should have a function or listener that updates us with the amount of bytes uploaded. This can be used to show the percentage of file uploaded.

**Describe alternatives you've considered**
Just show an infinite progress bar, until the upload completes

**Comment by alicejli** [comment]
@vipulm7 This feature request would be more appropriate for the Drive API team to implement, as this would be an API feature rather than a client library feature. Please submit this through one of the options on this page: https://developers.google.com/drive/api/support.

Closing this.
