### ISSUE TITLE
com.google.apis:google-api-services-sheets:v4-rev20230815-2.0.0 not found in maven central

### ISSUE THREAD

**Issue by warting** [googleapis/google-api-java-client-services#18375]
According to this page v4-rev20230815-2.0.0 is the latest version

https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-sheets/v4/2.0.0

```
repositories {
  mavenCentral()
}
dependencies {
  implementation 'com.google.apis:google-api-services-sheets:v4-rev20230815-2.0.0'
}
```

However, v4-rev20230815-2.0.0 is not found in maven central.
v4-rev20230815-2.0.0 can only be found here: https://central.sonatype.com/artifact/com.google.apis/google-api-services-sheets/versions

**Comment by meltsufin** [comment]
It's there: https://repo1.maven.org/maven2/com/google/apis/google-api-services-sheets/v4-rev20230815-2.0.0/
The link you gave *is* Maven Central.
