### ISSUE TITLE
Cloud SQL Admin - Cannot distinguish an instance is running or stopped via SqlInstanceState

### ISSUE THREAD

**Issue by bakoorjakkals** [googleapis/google-api-java-client-services#18426]
#### Description
I am trying to automatically stop SQL instances to save costs. 

My database instance was stopped using the Cloud SQL Admin API Client Library for Java by applying a patch and setting the activation policy to `NEVER` as described here: https://cloud.google.com/sql/docs/mysql/start-stop-restart-instance

After applying the patch, I confirmed on the GCP console that the database is in a stopped state.

I also ran the command `gcloud sql instances describe my-db-instance` which indicated that the instance state is `STOPPED`

However, attempting to get the state using the Cloud SQL Admin API Client Library for Java (or even using the RESTv1 or v1beta API) always returns that the instance is in a `RUNNABLE` state

I even tried starting and stopping the instance in the GCP console, but still get the same results.

#### Environment details

1. Specify the API: Cloud SQL Admin API Client Library for Java
2. OS type and version: Ubuntu 20.04
3. Java version: 17
4. SQL Admin version: google-api-services-sqladmin v1-rev20231004-2.0.0
5. Instance version: PostgreSQL 14

#### Steps to reproduce

  1. Stop a running instance, either by patching the activation policy setting and setting it to `NEVER`, or by using the GCP console.
  2. After the instance is stopped, check the instance state using Cloud SQL Admin API Client Library for Java or the Google REST API

#### Code example

```java
sqlAdmin.instances().patch(
    project,
    instanceName,
    new DatabaseInstance()
        .setSettings(
            new Settings()
                .set("activationPolicy", "NEVER")
        )
).execute();

DatabaseInstance instance;
do {
    instance = sqlAdmin.instances().get(project, instanceName).execute();
    logger.info("Database state of {}: {}", instance.getName(), instance.getState());
    // Returns RUNNABLE when instance is stopped
    if(!instance.getState().equals("STOPPED")) {
        Thread.sleep(5000);
    }
} while (!instance.getState().equals("STOPPED"));
```

```bash
curl -X GET     -H "Authorization: Bearer $(gcloud auth print-access-token)" "https://sqladmin.googleapis.com/sql/v1beta4/projects/my-project/instances/my-db-instance"
# Returns RUNNABLE when instance is stopped
```

```bash
gcloud sql instances describe my-db-instance
# Returns STOPPED when instance is stopped
```

#### External references such as API reference guides

https://cloud.google.com/sql/docs/mysql/start-stop-restart-instance

**Comment by suztomo** [comment]
> the Cloud SQL Admin API Client Library for Java

Can you share the Maven coordinates?

"STOPPED" and "RUNNABLE" may be categorized in different levels. Can you share the documentation you were reading with regard to the "STOPPED" and  "RUNNABLE" states?

**Comment by bakoorjakkals** [comment]
Here is the dependency included in my POM file:

```xml
<dependency>
    <groupId>com.google.apis</groupId>
    <artifactId>google-api-services-sqladmin</artifactId>
    <version>v1-rev20231004-2.0.0</version>
</dependency>
```

I also found this same issue mentioned in the Dotnet client repo: https://github.com/googleapis/google-api-dotnet-client/issues/1500, but it wasn't resolved.

In that issue it is mentioned that `STOPPED` is not a valid `SqlInstanceState` in the REST APIs (see here: https://cloud.google.com/sql/docs/postgres/admin-api/rest/v1beta4/instances#SqlInstanceState), but somehow gcloud is able to indicate a stopped state when the instance is stopped.

If that is the case, how can I determine if a database instance is stopped using the REST API or Java API client?

**Comment by suztomo** [comment]
In that document, RUNNABLE is "The instance is running, or has been stopped by owner." Indeed this value itself does not help your case.

Checking further.

**Comment by suztomo** [comment]
I couldn't find an alternative. Please follow jskeet's instruction at https://github.com/googleapis/google-api-dotnet-client/issues/1500#issuecomment-1778697639.
