### ISSUE TITLE
Quota Exceeded error does not specify the reason

### ISSUE THREAD

**Issue by haydin505** [googleapis/google-api-java-client-services#19074]
I'm trying to handle different quota restrictions but API returns same response for variety of quota limits. Could you please consider handling them separately? Also, why the reason and code in the response body is bad request? I would expect forbidden (http status code 403) here.

Current Response:
```
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Quota exceeded.",
    "reason" : "badRequest"
  } ],
  "message" : "Quota exceeded."
}
```

Expected Responses: 
-You have reached to maximum API calls for today. Error code: 2001
-You have reached to maximum data set for the property. Error code: 2002
-You have reached to maximum data size which is 1 GB. Error code: 2003

I'm using below API.
https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas#data_import

**Comment by haydin505** [comment]
https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas#data_import

**Comment by suztomo** [comment]
This repository is for the library generation for the API you're using. Would you follow the guide in Analytics documentation? https://developers.google.com/analytics/help
