### ISSUE TITLE
Drive File resource  does not return exportLinks for google form, google map

### ISSUE THREAD

**Issue by sonam-serchan** [googleapis/google-api-java-client-services#19919]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-java-client-services/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: Mac OS Sonoma 14.3.1 (23D60)
3. Java version: 17
4.  version(s):

#### Steps to reproduce

  1. Use file resource to get the available export links for exporting the google workspace documents such as google docs, slides, form, map etc.
  2. Export link if null for google form and map.

#### Code example

```java
return drive.files().get(id).setFields("*").setQuotaUser(GoogleDriveUtil.getUserString()).setSupportsAllDrives(true).execute();
```

#### Stack trace
```
No just exportLink is not returned in File response.
```

#### External references such as API reference guides

- https://developers.google.com/drive/api/guides/manage-downloads#export-content-browser
<img width="873" alt="Screenshot 2024-03-06 at 10 25 46" src="https://github.com/googleworkspace/java-samples/assets/23254380/fd435e46-72fa-4260-99ea-74d155f4c567">

#### Any additional information below

I am trying to export the google workspace documents. For this, I use export link from files resource to get the available download link for the document type. I can get for documents such as google doc, slide, spreadsheet etc. However, for google form, google map, I don't get the export links. Thus, cannot export the documents.

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by zhumin8** [comment]
This sounds more of a "Drive API" question than a "Java client libraries" question. Note that the maintainers of this repository don't have detailed knowledge of the APIs itself.  You might consider reaching out through Drive API's [support channels](https://developers.google.com/drive/api/support) instead.

With simple search, these looks likely limitations of Drive API. 
For Google Maps, there is a related feature request open [here](https://b.corp.google.com/issues/36760459).
For Google Forms, found some helpful links that might help with exporting to zip format:
https://stackoverflow.com/a/65525145
https://developers.google.com/drive/api/guides/ref-export-formats

**Comment by mpeddada1** [comment]
Closing this issue given the context provided in https://github.com/googleapis/google-api-java-client-services/issues/19919#issuecomment-1994640580. Please feel free to re-open this issue if you think this is still an issue related to the client library.
