### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by Rm-rmd** [googleapis/google-api-java-client-services#19977]
When getting responses of forms can't find the way to change timezone. Time of response creation by default in utc time. Unfortunately it's needed utc+2. Please help

**Comment by diegomarquezp** [comment]
Hi @Rm-rmd, thanks for reporting this. Would you mind sharing a small piece of code showing the missing timezone option? 

From the [docs](https://googleapis.dev/java/google-api-services-forms/latest/index.html), `Responses` is something you can either `list` or `get`, so I'm assuming you need to get the received responses from either of these methods converted to your own timezone. 

If all you want is to convert the timezone of your object to a specific offset, you can try something like
```java
OffsetDateTime odtB = OffsetDateTime.parse("2018-03-26T06:00:00Z");
odtB = odtB.plusHours(2);
```

**Comment by diegomarquezp** [comment]
Glad it worked.

> get already formed utc+2 from the server

Looks like the [api definition](https://github.com/googleapis/discovery-artifact-manager/blob/master/discoveries/forms.v1.json) of `forms/v1` does not support any sort of offset setting.

I would suggest some client side interceptor for your calls using the snippet above.

I'll be closing this issue now - feel free to reopen it if you have more questions. Thanks!
