### ISSUE TITLE
Google Cloud Commerce Partner Procurement API

### ISSUE THREAD

**Issue by sandeep-khanna** [googleapis/google-api-java-client-services#21582]
Is there a reason why this collection does not include the [Google Cloud Commerce Partner Procurement API](https://cloud.google.com/marketplace/docs/partners/commerce-procurement-api/reference/rest) cloud client library?

Elsewhere on GitHub, I have requested the conversion and addition of the Google Cloud Commerce Partner Procurement OpenAPI spec in YAML. This could be used to generate a Java client library using something like [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator#openapi-generator).

- [Issue#23@google-discovery-to-openapi](https://github.com/stackql/google-discovery-to-openapi/issues/23)
- [Issue#36@google-discovery-to-swagger](https://github.com/APIs-guru/google-discovery-to-swagger/issues/36)

**Comment by lqiu96** [comment]
Added context here about the API: https://github.com/googleapis/google-cloud-java/issues/10861#issuecomment-2123281958

As of now, there is no ETA for adding a library for the `Partner` API. Going to close this ticket, but feel free to re-open if you have any other questions.
