### ISSUE TITLE
Semantic versioning? Release notes?

### ISSUE THREAD

**Issue by ccudennec-otto** [googleapis/google-api-java-client-services#21906]
**Is your feature request related to a problem? Please describe.**
We frequently get Dependabot PRs to update your libraries: This is how it looks like:
```
Bump com.google.apis:google-api-services-run from v2-rev20240412-2.0.0 to v2-rev20240524-2.0.0
```

Dependabot is just not able to find your release notes and does not link it in the PR description.
But that's not just a Dependabot issue: When I investigate the PRs I have not succeeded in finding the documentation for the changes and since you're not using semantic versioning, it's really hard to understand the changes and the impact/risk of merging the PR.

Everything that we see in the version change is a build date - nothing else.

**Describe the solution you'd like**
Please document your changes here in Github.
* You can tag the versions here: https://github.com/googleapis/google-api-java-client-services/releases
* You can add a "CHANGES.md" or "RELEASE_NOTES.md" to your repo

You can also make it more understandable and obvious by changing your version pattern to [semantic versioning](https://semver.org/). This would instantly help the consumers of your libraries.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by diegomarquezp** [comment]
@suztomo the version changes are meant to be reflections of changes in their discovery docs. However our source of truth for these docs [doesn't contain any messages](https://github.com/googleapis/discovery-artifact-manager/commits/master/discoveries) 
Implementing commit messages for these changes seems not trivial, as the discovery update job simply fetches everything from a single general URL:
https://github.com/googleapis/discovery-artifact-manager/blob/97dca7babe661bba350f9f76b116d5ee87661dc6/scripts/update_disco.py#L92-L97

**Comment by ccudennec-otto** [comment]
What is your recommendation for new versions that only have a new timestamp? Is it always save to update?
How can you decide if the automatic changes contain any significant changes? At some place you should change the patch or minor version of the next release, shouldn't you?

I.e. instead of "v2-rev20240524-2.0.0" it should be "v2-rev20240524-2.1.0" if the next release contains new features IMHO.

**Comment by diegomarquezp** [comment]
@ccudennec-otto Our library generation workflow relies on https://discovery.googleapis.com/discovery/v1/apis which does not provide information on the changes made in each library, so the generation workflow that uses this service cannot generate release notes for the libraries.

Regarding the version string, it has two components: the revision (e.g. `rev20240607`) (associated to the discovery document, with changes to the API definition) and the generator version (e.g. `2.0.0`) which contains the logic for generating the library given a discovery doc.

Although this is a valid feature request, it would require deep changes beyond this java repository, so we will close this as infeasible.

**Comment by ccudennec-otto** [comment]
Thanks for taking the time to look into this and respond to my request. 🌻 

As last comment / recommendation: I can only recommend to help your consumers get a better understanding of the impact of your changes. Try to add semantic versioning to this project and/or documentation of the changes. As a consumer having only a random version number (as a consumer) and no documentation really is painful.
