### ISSUE TITLE
The subscriptionsv2 api does not return price and currency?

### ISSUE THREAD

**Issue by hakusai22** [googleapis/google-api-java-client-services#22351]
The subscriptionsv2 api does not return price and currency?

- https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2#SubscriptionPurchaseLineItem
<img width="1758" alt="image" src="https://github.com/googleapis/google-api-java-client/assets/58761705/24fc901b-0333-4b16-a314-f5959e172f61">

<img width="1626" alt="image" src="https://github.com/googleapis/google-api-java-client-services/assets/58761705/218e580d-d97c-49ba-905c-1f940bb295cb">

**Comment by Shanzay009** [comment]
44

**Comment by hakusai22** [comment]
> 44

？
