### ISSUE TITLE
Some 1.30.3 generated libraries not found in Maven central

### ISSUE THREAD

**Issue by qtxo** [googleapis/google-api-java-client-services#3007]
For example Admin Reports: https://github.com/googleapis/google-api-java-client-services/tree/master/clients/google-api-services-admin/reports_v1

Shows:
```
<project>
  <dependencies>
    <dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-admin-reports</artifactId>
      <version>reports_v1-rev20190521-1.30.3</version>
    </dependency>
  </dependencies>
</project>
```
But can't be found in Maven, version reports_v1-rev20190521-1.30.1 is fine.

**Comment by codyoss** [comment]
Thanks for the report @qtxo . It looks like this might be related to #2607.

**Comment by qtxo** [comment]
This is still broken after one month, any idea when the libraries are going to be created or the READMEs fixed?

**Comment by chingor13** [comment]
Sorry, this was fixed in February and the latest libraries are available on Maven Central.
