### ISSUE TITLE
listManagementGoals

### ISSUE THREAD

**Issue by webmarketingleas** [googleapis/google-api-java-client-services#3131]
We are trying to run the following code but it doesn't work.
We are trying to print goals
Any ideas ?
Thank you

$goals = new Google_Service_Analytics_Goal();
$goals = $analytics->management_goals->
listManagementGoals('123456', 'UA-123456-1', '~all');

$items = $goals->getItems();

foreach ($items as $gol){
    print_r($gol);
}

**Comment by codyoss** [comment]
Can you please provide more details. Versions used, error you are getting, what you expect. Thanks
