### ISSUE TITLE
Version confusion in google-api-services-storagetransfer

### ISSUE THREAD

**Issue by elharo** [googleapis/google-api-java-client-services#3204]
https://github.com/googleapis/google-api-java-client-services/blob/master/clients/google-api-services-storagetransfer/v1/README.md suggests using version 1.30.3 but the newest in this repo is 1.30.1.

Also, why are there several version of this from 1.25.0 to 1.30.1?

**Comment by codyoss** [comment]
We can keep this open for now, but this is not unique to this artifact. See #3007 with a similar report

**Comment by danoscarmike** [comment]
Actually this seems to be fixed now: 
Maven has the version now suggested by the README (1.30.9)
https://search.maven.org/artifact/com.google.apis/google-api-services-storagetransfer/v1-rev20200316-1.30.9/jar
