### ISSUE TITLE
Isn't there a firewall client to add rules to App Engine Standard?

### ISSUE THREAD

**Issue by UlisesCeca** [googleapis/google-api-java-client-services#3263]
Hello. I've been about 2 days trying to add rules to the firewall in App Engine without success. The closes I was was to add rules using the API REST, but appareantly I need Oauth2 for that and I've also read that it's better to use client libraries, so here I am.

However, I can't seem to find this library, I thought it'd be on this library but I also can't find anything to add rules.

Isn't there some library to do this? Or will I have to go with the API REST?

Thanks!

**Comment by codyoss** [comment]
Are you looking for this: https://github.com/googleapis/google-api-java-client-services/blob/master/clients/google-api-services-appengine/v1/1.30.1/com/google/api/services/appengine/v1/model/FirewallRule.java#L31

If you are wondering more about auth, this might be what you want: https://github.com/googleapis/google-auth-library-java#using-credentials-with-google-http-client
