### ISSUE TITLE
Failed to resolve: com.google.apis:google-api-services-youtube:v3-rev20200109-1.30.3

### ISSUE THREAD

**Issue by yokei15** [googleapis/google-api-java-client-services#3691]
Facing failed to resolve issues in latest version in Android.

**ERROR: Failed to resolve: com.google.apis:google-api-services-youtube:v3-rev20200109-1.30.3**

`implementation 'com.google.apis:google-api-services-youtube:v3-rev20200109-1.30.3'`

**Comment by ElegyD** [comment]
1.30.8 is now available through maven.
`implementation 'com.google.apis:google-api-services-youtube:v3-rev20200109-1.30.8'`
