### ISSUE TITLE
Storage Object name encoding

### ISSUE THREAD

**Issue by cchantep** [googleapis/google-api-java-client-services#3783]
The [documentation](https://cloud.google.com/storage/docs/request-endpoints) states that "encoding is typically handled for you by client libraries, such as the Cloud Storage Client Libraries, so you can pass the raw object name to them", but with an object name like `Capture d’écran 2018-11-14 à 09.35.49.png` (obtained from list from `Storage.objects()`), operations (such as delete) are refused with a 404 not found error.

```javascript
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "No such object: .../Capture+d’écran+2018-11-14+à+09.35.49.png",
    "reason" : "notFound"
  } ],
  "message" : "No such object: .../Capture+d’écran+2018-11-14+à+09.35.49.png"
}
```

**Comment by chingor13** [comment]
Which client library are you trying to use? `com.google.cloud:google-cloud-storage` or `com.google.apis:google-api-services-storage`?

**Comment by athakor** [comment]
@chingor13 same issues [#121](https://github.com/googleapis/java-storage/issues/121),[#57](https://github.com/googleapis/java-storage/issues/57)

**Comment by frankyn** [comment]
Hi @cchantep, could you try using the latest release of `com.google.cloud:google-cloud-storage` if this is what you're using? The issue was resolved last week in the latest release. 

If it's related to `com.google.apis:google-api-services-storage` please confirm. 

Will close issue if no further follow-up.

**Comment by frankyn** [comment]
Please reopen if the issue persists. Thank you for filing the issue!
