### ISSUE TITLE
google-api-services-drive v3-rev20191108-1.30.8 not found in maven central

### ISSUE THREAD

**Issue by hatanaka-akihiro** [googleapis/google-api-java-client-services#3802]
Accoding to this page

https://github.com/googleapis/google-api-java-client-services/tree/master/clients/google-api-services-drive/v3

```xml
<project>
  <dependencies>
    <dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-drive</artifactId>
      <version>v3-rev20191108-1.30.8</version>
    </dependency>
  </dependencies>
</project>
```

However, v3-rev20191108-1.30.8 is not found in maven central.
v3-rev20191108-1.30.3 is latest.

**Comment by chingor13** [comment]
Apologies, we had a delay with our publishing pipeline for these clients - this is available on Maven Central: https://search.maven.org/artifact/com.google.apis/google-api-services-drive/v3-rev20191108-1.30.8/jar
