### ISSUE TITLE
How can I get sales country with this Google Play Developer API for Java?

### ISSUE THREAD

**Issue by choiis** [googleapis/google-api-java-client-services#3850]
Hello I am Mr.Choi from south korea.
I'm using google-api-services-androidpublisher V3 now
I'm supposed to get list of sales country to using publish api.
How can I get sales country with this API?

and I tried to get countryTargeting in tracks.
But getCountryTargetings method always returned null.
Why did the method return null, and What does countryTargeting means?

Thanks

**Comment by jayal** [comment]
Is there any update on this issue? We are using https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#Track API to get/update the list of Countries for a given Track. 

Is this a known issue? Can anyone please point to a working example of the API?

**Comment by jayal** [comment]
@chingor13 Could you please help point us in the right direction? We are currently unable to find any data to help us resolve this issue. 

We are using the Google API for Google Play Console that is documented here - https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks/get. The request we are using is 

Request Parameters - 
applicationId - <some-application-id>
track - alpha
editID - <Generated by created via https://developers.google.com/android-publisher/api-ref/rest/v3/edits/insert) 

Response : `{"releases":[{"name":"228.0.2","releaseNotes":[{"language":"en-US","text":"Bug fixes"}],"status":"completed","versionCodes":["228000002"]}],"track":"alpha"}`

**The response is missing** "`CountryTargeting`" - https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#countrytargeting 

The service account used in the account has full admin level access to the Google Play Console account
