### ISSUE TITLE
When Upgrade to python3

### ISSUE THREAD

**Issue by MarsYoung** [googleapis/google-api-java-client-services#4215]
https://www.python.org/doc/sunset-python-2/

And my problem is :
Execute:
     python2 -m pip install -e generator/ --user

ERROR: Package 'cachetools' requires a different Python: 2.7.16 not in '~= 3.5'

**Comment by chingor13** [comment]
This is a prioritization question. The generator is not intended for external use at this time and the upgrade is non-trivial.

**Comment by chingor13** [comment]
Duplicate of #551
