### ISSUE TITLE
v3.4-rev20200121-1.30.9 MatchId Uncompilable source code - Erroneous tree type

### ISSUE THREAD

**Issue by lordrobertox** [googleapis/google-api-java-client-services#4246]
Hi,

After upgrading to the version v3.4-rev20200121-1.30.9, all MatchId conversions report this error.

"Uncompilable source code - Erroneous tree type: com.google.api.services.dfareporting.Dfareporting"

Any help will be apreciate.

**Comment by burkedavison** [comment]
Closing this issue as we are unable to provide adequate customer support through this forum. https://cloud.google.com/support is best able to provide timely answers to API-specific questions.
