### ISSUE TITLE
BigQuery api timestamp in millis failed to insert

### ISSUE THREAD

**Issue by bindiego** [googleapis/google-api-java-client-services#4337]
version: `v2-rev20191211-1.30.9`

As the BigQuery can deal with timestamp data in millis and micros. But when using [TableRow](https://www.javadoc.io/doc/com.google.apis/google-api-services-bigquery/v2-rev20191211-1.30.9/com/google/api/services/bigquery/model/TableRow.html#set-java.lang.String-java.lang.Object-) `set` method, I still need to convert to seconds in order to make it work.

I have the raw data in `long` type, that can be inserted into BigQuery `INTEGER` field. But for BigQuery `TIMESTAMP`, I can keep the `long` type in java but need to convert to `seconds` level.

Did I miss something? e.g. [here](https://github.com/bindiego/raycom/commit/59acb2e381e7d71bc78d60fee3ed5114620ed7fe) is the change I made it works in dataflow but lost precisions. 

Thanks a lot.

**Comment by pmakani** [comment]
@bindiego this is legacy client, so could you please use a new client [java-bigquery](https://github.com/googleapis/java-bigquery) , for new client you can use  `InsertAllRequest` and  for legacy client  you can use `TableDataInsertAllRequest`, However, new client has more functionality and controls then legacy client,
