### ISSUE TITLE
When can I start using another timezone?

### ISSUE THREAD

**Issue by yjystyle** [googleapis/google-api-java-client-services#4404]
HI,
My name is junyeong,
and I've been developed by **admob api** to provide report to marketing department.

My county is in Korea. so we want to use _"Asia/Seoul"_ Timezone that is GMT+9. 
But you know, Admob API provides only _"America/Los Angeles"_ Timezone for now.

So I'm wondering when I can use _"Asia/Seoul"_timezone?

**Comment by chithuan102** [comment]
I have the same problem. My timezone is GMT+7 (_Asia/Ho_Chi_Minh_)

**Comment by burkedavison** [comment]
Closing this issue as we are unable to provide adequate customer support through this forum. https://cloud.google.com/support is best able to provide timely answers to API-specific questions.
