### ISSUE TITLE
Link for documentation points to v3, not v2

### ISSUE THREAD

**Issue by jonutah** [googleapis/google-api-java-client-services#4513]
Link for Javadoc reference documentation points to v3 of the documentation, not v2. I know this because there is no Files.insert method in the docs currently being pointed to.

**Comment by danoscarmike** [comment]
@jonutah thanks for reaching out. Can you clarify which API/service you are using? Can you paste the link?

**Comment by felipebueno** [comment]
@danoscarmike this is the link 

https://developers.google.com/drive/api/v2/reference/files/insert?apix_params=%7B%22convert%22%3Atrue%2C%22resource%22%3A%7B%7D%7D#examples

**Comment by danoscarmike** [comment]
Apologies but I'm still not clear on where @jonutah has found the incorrect link to javadoc? Is it in the README for drive v2?

**Comment by felipebueno** [comment]
I was following the Java example on that page and I had the same problema as @jonutah.

It has a call to ```service.files().insert(...)``` wich does not exist in the current stable api (I think it is```com.google.apis:google-api-services-drive:v3-rev110-1.23.0```) .
 
![image](https://user-images.githubusercontent.com/241271/84947316-613fc500-b0c0-11ea-9663-9df2e6ec5490.png)

**Comment by danoscarmike** [comment]
@felipebueno the page you linked is explicitly related to the v2 API which does expose a Drive.files().insert() method. You are correct that v3 does not. The equivalent reference for v3 is here: https://developers.google.com/drive/api/v3/reference/files/

However I believe @jonutah may have encountered a different issue - the original post refers to finding the *v3* docs when *v2* was expected.

**Comment by meredithslota** [comment]
I can't repro what @jonutah was reporting — closing this due to relative staleness but please reopen or file a new issue if you find other broken or incorrect links. Thanks!
