### ISSUE TITLE
The read the Developer's Guide link points to gitHub, not the guide.

### ISSUE THREAD

**Issue by jonutah** [googleapis/google-api-java-client-services#4514]
The "read the Developer's Guide for the Google API Client Library for Java" should point here:

https://developers.google.com/api-client-library/java/google-api-java-client/dev-guide

**Comment by chingor13** [comment]
Let's actually point them here: https://googleapis.github.io/google-api-java-client/

**Comment by eaball35** [comment]
Fixed this with https://critique-ng.corp.google.com/cl/346883381
