### ISSUE TITLE
Using GoogleNetHttpTransport.newTrustedTransport() Behind Proxy

### ISSUE THREAD

**Issue by rhysowen9** [googleapis/google-api-java-client-services#4656]
Hi All,

I'm using `google-api-services-admin-directory` version `directory_v1-rev118-1.25.0` and in a clean environment, following the docs, everything seems to work as expected.

I am using the service as follows:

```
Directory service = new Directory.Builder(
    GoogleNetHttpTransport.newTrustedTransport(),
    JacksonFactory.getDefaultInstance(), 
    new HttpCredentialsAdapter(accountCredentials)
).setApplicationName(applicationName).build();
```

However, as soon as I go into my proxied environment, I get the following error:

```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Having had a bit of a Google, I've tried lots of suggestions, including downloading certificates and adding them to my JDK trust store, adding proxy information via JDK flags, etc.

But none of this worked. What _did_ work, however, was using `new NetHttpTransport()` instead of `GoogleNetHttpTransport.newTrustedTransport()`.

But this is not even an option suggested in the docs:

```
transport - HTTP transport, which should normally be:
Google App Engine: com.google.api.client.extensions.appengine.http.UrlFetchTransport
Android: newCompatibleTransport from com.google.api.client.extensions.android.http.AndroidHttp
Java: com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()
```

Is there any reason the docs does not suggest `new NetHttpTransport()` as an option? Am I compromising on security by not using the trusted transport?

**Comment by chingor13** [comment]
IIRC, the GoogleNetHttpTransport adds trusted Google keys for request verification. If you're using the client directly against Google endpoints it's working. If you're hitting your proxy server which is intercepting requests, then the transport is not necessarily trusted.

**Comment by rhysowen9** [comment]
Hi @chingor13 , I agree that that is the case, but is it necessarily a _bad idea_ to swap out the trusted transport for the `NetHttpTransport`?

**Comment by chingor13** [comment]
I cannot comment on whether or not you should do that - you can provide your own `HttpTransport`, but not using the Google provided keys is less secure than using them.

You should be able to configure the http proxy and use our certificates as well.
