### ISSUE TITLE
Google-Bigquery V2 API - exception in update operation using jobs.query API

### ISSUE THREAD

**Issue by shrgupta28** [googleapis/google-api-java-client-services#4663]
Hi Team,

I am using **jobs.query** API to update the table records in bigquery.

To check the stability, we run the code for several hours.
While running the Stability tests - exception occurs for the update operation after the project is in running state for 4:30 hrs, 11 hours, and after 17 hrs. This is observed at various different intervals.

The strange thing is, **no error message is returned from bigquery**. 
We tried by drilling down, and it seems, the exception error message, cause, and stack trace are blank and do not provide any information about the issue.

We face the similar issue while we run concurrency as well.

Can you please help us with this?

Environment:
Java 1.8
Google Bigquery API V2 - google-api-services-bigquery-v2-rev20200415-1.30.9.jar

**Comment by shrgupta28** [comment]
@danoscarmike Request your team's help on this. We are stuck with this in our development.

**Comment by danoscarmike** [comment]
@shrgupta28 can you provide some more detail on the code and environment so we could try to reproduce?

**Comment by shrgupta28** [comment]
@danoscarmike I am using JAVA API jobs.query to update the records in bigquery.

PFA the sample code.. 
[UpdateTest.txt](https://github.com/googleapis/google-api-java-client-services/files/4714967/UpdateTest.txt)

I request your help on this. 
We are facing the same issue while running stability and concurrency Tests.

Thanks,
Shruti Gupta

**Comment by danoscarmike** [comment]
@shrgupta28 I can only encourage that you migrate to the recommended client for [BigQuery](https://github.com/googleapis/java-bigquery). You will find much better support there.

**Comment by shrgupta28** [comment]
@danoscarmike We are in the final development phase and using BigQuery V2 API. Can you please help us with the solution using this API. 
I see this is another API that you are recommending. We might not be able to migrate to this at this moment. We might keep it for future references. 
Thanks.

**Comment by meredithslota** [comment]
Hello @shrgupta28 — the other client library still calls the same BigQuery v2 API: https://github.com/googleapis/java-bigquery Documentation and code samples for running query jobs can be found here: https://cloud.google.com/bigquery/docs/running-jobs#bigquery_create_job-java and here: https://cloud.google.com/bigquery/docs/running-queries#bigquery-query-api
