### ISSUE TITLE
Authentication using Service Account key

### ISSUE THREAD

**Issue by shrgupta28** [googleapis/google-api-java-client-services#4665]
Hi Team,

I am using Java 1.8 along with the Google Bigquery V2 API, latest revision. 

I am using a service account key-based authentication mode. 
I am using the below class to create the credentials, but it is deprecated.      

------------------------------------------------------------------------------------------
                HttpTransport transport = new NetHttpTransport();
		JsonFactory jsonFactory = new JacksonFactory();

		InputStream credentialStream = new FileInputStream(new File(jsonFilePath));
		GoogleCredential credential = GoogleCredential.fromStream(credentialStream, transport, jsonFactory);
		if (credential.createScopedRequired()) {
			credential = credential.createScoped(BigqueryScopes.all());
		}

		Bigquery bigquery = new Bigquery.Builder(transport, jsonFactory, credential).setApplicationName("BigqueryApplication").build();
------------------------------------------------------------------------------------------

can you please help me with the new API that I can use for this authentication.

Thanks,
Shruti

**Comment by pmakani** [comment]
@shrgupta28 This is legacy bigquery client. could you please try to use new bigquery client which has better functionality ? [google-cloud-bigquery](https://github.com/googleapis/java-bigquery)

**Comment by shrgupta28** [comment]
@pmakani We are already using this API in our product. Switching to a new one at this point won't be feasible.

**Comment by pmakani** [comment]
@shrgupta28 can you please use `GoogleCredentials` instead of `GoogleCredential`

**Comment by shrgupta28** [comment]
I am using `com.google.api.client.googleapis.auth.oauth2.GoogleCredential `
In the same package, there is no API called GoogleCredentials

**Comment by danoscarmike** [comment]
@shrgupta28 `google-auth-library` is recommended now. 

Here's a [snippet](https://github.com/googleapis/google-auth-library-java#using-credentials-with-google-http-client) which outlines usage with the `google-api-java-client`

**Comment by shrgupta28** [comment]
@danoscarmike Thanks for this, but I get the below error when I try to use this code. can you help me resolve this... 
[BigQueryClientAuth.txt](https://github.com/googleapis/google-api-java-client-services/files/4649885/BigQueryClientAuth.txt)


Exception in thread "main" java.io.IOException: Scopes not configured for service account. Scoped should be specifed by calling createScoped or passing scopes to constructor.
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:183)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:76)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:53)

**Comment by pmakani** [comment]
@shrgupta28 please try below code for scope.
`GoogleCredentials.fromStream(credentialStream).createScoped(BigqueryScopes.all());`

**Comment by shrgupta28** [comment]
Thanks a lot, this works! Appreciate your quick help. :)
