### ISSUE TITLE
Null values are displayed as java.lang.Object@674621fd while performing select using the jobs.query API in java

### ISSUE THREAD

**Issue by shrgupta28** [googleapis/google-api-java-client-services#4666]
Hi Team,

While using **jobs.query API** to select the data from bigquery table, NULL values in the table are returned as object hashcode *java.lang.Object@674621fd*. 

I want to retrieve those null values as null only. Can you please help me with this?

Below is the code I am using:

----------------------------------------------------------------------------------
QueryResponse query = bigquery.jobs().query(projectId, new QueryRequest().setQuery(querySql)).execute();

		for (TableRow row : query.getRows()) {
			for (TableCell field : row.getF()) {
				System.out.print(field.getV());
				System.out.println();
			}
			System.out.println();
		}
----------------------------------------------------------------------------------

Thanks,
Shruti

**Comment by pmakani** [comment]
@shrgupta28 This is legacy bigquery client. could you please try to use new bigquery client which has better functionality ? [google-cloud-bigquery](https://github.com/googleapis/java-bigquery)

**Comment by shrgupta28** [comment]
@pmakani Can you help me resolve this with the legacy API itself. Moving to a new API is not feasible at this point.

**Comment by shrgupta28** [comment]
@pmakani @danoscarmike Request your help on this. The null values from the bigquery are returned as  `java.lang.Object@674621fd`.  
Below is the code snippet I am using.
[sample.txt](https://github.com/googleapis/google-api-java-client-services/files/4650057/sample.txt)

**Comment by pmakani** [comment]
@shrgupta28 value return as object so you need to cast according to data types or you can refer this  [Bigquery Client](https://github.com/googleapis/java-bigquery/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldValue.java)  library and it's wrapper of this bigquery client.

**Comment by shrgupta28** [comment]
@pmakani This is from google cloud bigquery. I am using the Bigquery v2 API

**Comment by pmakani** [comment]
@shrgupta28 it's wrapper of Bigquery V2 API.

**Comment by shrgupta28** [comment]
@pmakani Can you help me with the code snippet. How I can use FieldValue in my call. 
PFA the my code.
[sample.txt](https://github.com/googleapis/google-api-java-client-services/files/4651691/sample.txt)

**Comment by shrgupta28** [comment]
@pmakani Request your help on this.. we are stuck with this in our development.

**Comment by shrgupta28** [comment]
This is resolved using the Cloud BigQuery Wrapper
