### ISSUE TITLE
CalendarList.insert(CalendarListEntry).execute is returning 404

### ISSUE THREAD

**Issue by ucdmahynes** [googleapis/google-api-java-client-services#5794]
Hello,

There seems to be some issue. This was working in the past but recently stopped working. Trying to subscribe a user to an existing calendar, or in other words inserting an existing calendarId into the CalendarList. The Api documentation says to do the following:

CalendarList.insert(CalendarListEntry).execute

However this now returns a 404 on the URL https://www.googleapis.com/calendar/v3/users/me/calendarList

The API Explorer online also gets a 404 when trying to execute it

**Comment by chingor13** [comment]
Please open an issue on the [GSuite Calendar issue tracker](https://issuetracker.google.com/issues/new?component=191627&template=0). Our client library appears to be making the correct request, but the actual service is behaving incorrectly.

**Comment by danoscarmike** [comment]
Closing this issue as inactive. @ucdmahynes please feel free to comment if you would like additional help.
