### ISSUE TITLE
Build with R8 minifyEnabled Bug

### ISSUE THREAD

**Issue by MaxAndolini** [googleapis/google-api-java-client-services#6131]
I saw warnings on google play that I need to turn on minifyEnabled. When I activate it, I get these warnings while compiling and the library I use for google play subscriber control (android publisher) is not working on released APK but it works fine on android studio emulator runtime.

```
    Android Studio 4.1
    Android Gradle Plugin: 4.1.0
    Gradle: 6.6.1
```

I tried some proguard settings but they are not working.

```
    > Task :app:minifyReleaseWithR8
    AGPBI: {"kind":"warning","text":"Missing class: javax.servlet.ServletContextListener","sources":[{}],"tool":"R8"}
    AGPBI: {"kind":"warning","text":"Missing class: java.lang.ClassValue","sources":[{}],"tool":"R8"}
    Missing class: javax.servlet.ServletContextListener
    
    Missing class: java.lang.ClassValue
```

**Comment by lesv** [comment]
Please file a question with the [Android](https://support.google.com/googleplay/android-developer/gethelp) team.
