### ISSUE TITLE
android-publisher GET Track API call does not return CountryTargeting

### ISSUE THREAD

**Issue by jayal** [googleapis/google-api-java-client-services#6270]
We are using the Google API for Google Play Console that is documented here - https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks/get. The request we are using is

Request Parameters -
applicationId -
track - alpha
editID - <Generated by created via https://developers.google.com/android-publisher/api-ref/rest/v3/edits/insert)

Response : {"releases":[{"name":"228.0.2","releaseNotes":[{"language":"en-US","text":"Bug fixes"}],"status":"completed","versionCodes":["228000002"]}],"track":"alpha"}

The response is missing "CountryTargeting" - https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#countrytargeting

The service account used in the account has full admin level access to the Google Play Console account

**Comment by chingor13** [comment]
This looks like an backend service issue - the client can only parse what it receives from the endpoint. You can contact that team: https://support.google.com/googleplay/android-developer/answer/7218994
