### ISSUE TITLE
Can I use the Organization and Folder APIs at the same time?

### ISSUE THREAD

**Issue by hailey21** [googleapis/google-api-java-client-services#6365]
I understand that the organization API is only provided by v1 version and the folder information is provided by v2 API. What I need is the overall organizational structure. After granting permission to all organizations, folders and projects, I tried to view the entire structure, but the packages and classes of both versions of the API are the same, so they cannot be used at the same time. Is there no way I can use it?

I am using java, springboot and in maven,
I'm using the
<groupId>com.google.apis</groupId>
<artifactId>google-api-services-cloudresourcemanager</artifactId>
dependency. (currently, using v2-rev20201019-1.30.10 version)

For reference, the API documentation I referenced is this. ::
https://cloud.google.com/resource-manager/reference/rest/v1/organizations/get
https://cloud.google.com/resource-manager/reference/rest/v2/folders/list

I want to search the folder structure under each organization. Currently, only the folder structure can be viewed, and only the ID of the parent (organization) item can be checked through the parent property of the folder. We look forward to using this ID to look up the organization's name.

Thanks,

**Comment by chingor13** [comment]
Unfortunately, these artifacts are in separate maven versions so they cannot be used together directly. It's possible to use the maven-shade-plugin to repackage one of those libraries.

We're looking into easier ways to provide both APIs.

**Comment by chingor13** [comment]
The Cloud Resource Manager service released a v3 API which should contain the functionality of both v1 and v2. https://github.com/googleapis/google-api-java-client-services/tree/master/clients/google-api-services-cloudresourcemanager/v3
