### ISSUE TITLE
Analytics Reporting: Provide support for Google Auth Library

### ISSUE THREAD

**Issue by mariussoutier** [googleapis/google-api-java-client-services#6997]
`AnalyticsReporting.Builder` expects a `HttpRequestInitializer`, which is an interface that `com.google.api.client.googleapis.auth.oauth2.GoogleCredential` implements but which in turn is deprecated and should be replaced with `com.google.auth.oauth2.GoogleCredentials` which of course does not implement `HttpRequestInitializer` :-)

So please support using `com.google.auth.oauth2.GoogleCredentials`.

**Comment by chingor13** [comment]
This is already supported. We provide a `HttpCredentialsAdapter` which wraps a `com.google.auth.oauth2.GoogleCredentials` as a `HttpRequestInitializer`. See https://github.com/googleapis/google-auth-library-java#using-credentials-with-google-http-client for an example.

**Comment by mariussoutier** [comment]
Thanks, that works. This should be reflected in the API documentation.
