### ISSUE TITLE
Analytics Reporting: no rows returned when ga:campaignCode is specified

### ISSUE THREAD

**Issue by mariussoutier** [googleapis/google-api-java-client-services#7024]
As the title states, as soon as I want to query data that includes the dimension `ga:campaignCode` (utm_id), no rows are returned, instead of returning the data and setting campaignCode to (not set) as usual.

I also found an old issue talking about the same problem:
https://github.com/jlavitt/analytics-issues/issues/677

This can also be reproduced using [Query Explorer](https://ga-dev-tools.appspot.com/query-explorer/). As soon as you add `ga:campaignCode` as a dimension, no data is returned (at least for rows where it's empty). Same in Google Analytics custom reports.

**Comment by Neenu1995** [comment]
The Google Analytics team will be able to better assist you in this matter.
Here is a link to the [Google Analytics API support page](https://developers.google.com/analytics/help). 
The [public issue tracker](https://issuetracker.google.com/issues?q=componentid:187400) link provided in the document will help you find any known issues or file a new one.
