### ISSUE TITLE
Google Play Developer API: Unable to query dynamically inserted products from Play Console

### ISSUE THREAD

**Issue by WaluAier** [googleapis/google-api-java-client-services#7684]
I am not sure if the issue I will be describing is a bug in the Google Play billing library or the AndroidPublisher API but I haven't been able to find any answers and hope to have this fixed. Also, please note that I am not getting any errors for this one.

So, I'm trying to query all my in-app products using the GooglePlay Billing library in my client app by passing all my skus stored in a list to the SkuDetailsParams as such:

```
SkuDetailsParams params = SkuDetailsParams.newBuilder()
                        .setType(INAPP)
                        .setSkusList(skuList)
                        .build();
```

However, upon calling the querySkuDetailsAsync() method in my client app, it only seems to return a list containing the SkuDetails of the products that have been added MANUALLY to the Play Console but doesn't return any details for the dynamically added ones even though they are all active and visible in the Console which I find to be very strange!

```
billingClient.querySkuDetailsAsync(params,
            (billingResult, skuDetailsList) -> {
                System.out.println("size:"+skuDetailsList.size());
                if (billingResult.getResponseCode() != BillingClient.BillingResponseCode.OK) {
                    System.out.println(String.format("Unable to query sku details: %d - %s", billingResult.getResponseCode(), billingResult.getDebugMessage()));
                } else {
                    for (SkuDetails details: skuDetailsList) {
                        System.out.println("title -> "+details.getTitle());
                        System.out.println("description -> "+details.getDescription());
                        System.out.println("price -> "+details.getPrice());
                    }

                    setRecyclerView(skuDetailsList);
                }
            });

```
But since I want to insert the products dynamically, I have implemented the AndroidPublisher library and have called the inappproducts.insert() method to insert products to Play Console which gets added successfully BUT doesn't load in the client app until only several hours later. Note that this isn't the case when I manually add products via the Console as it loads immediately in-app. So what could be the problem here...

I've used the following code to insert products to Google Play Console dynamically.
```
//insert new product
    InAppProductListing listing = new InAppProductListing();
    listing.setTitle("my product");
    listing.setDescription("this is a description");
    Map<String,InAppProductListing> mapListing = new HashMap<String, InAppProductListing>();
    mapListing.put("en-GB", listing);

    Inappproducts inappproducts = pub.inappproducts();
    InAppProduct product = new InAppProduct();
    product.setDefaultLanguage("en-GB");
    product.setPackageName(packageName);
    product.setSku(productID);
    product.setPurchaseType("managedUser");
    product.setListings(mapListing);
    Price price = new Price();
    price.setCurrency("INR");
    price.setPriceMicros("50000000");
    product.setDefaultPrice(price);
    product.setStatus("active");
           
    try {
        inappproducts.insert(product.getPackageName(), product).setAutoConvertMissingPrices(true).execute();
        System.out.println("Success");
    } catch (Exception e) {
        // TODO: handle exception
    }
```

**Comment by lesv** [comment]
Please refile this issue with the [Google Play](https://support.google.com/googleplay/android-developer/gethelp) team.
