### ISSUE TITLE
Question (People API) : any way to query the otherContacts list by time updated?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleapis/google-api-java-client-services#7941]
Or maybe it's already sorted as such?
I want to cache the results and later if there is none on the query, ignore them all.
Or to update what's cached when possible.
This is why I also need some ID for each, but no idea where can I get it.

I'm talking about the API of `OtherContacts.list()` , which matches to [this](https://developers.google.com/people/api/rest/v1/otherContacts/list ), and returns me a list of `Person` (relevant link [here](https://developers.google.com/people/api/rest/v1/people#Person))

**Comment by AndroidDeveloperLB** [comment]
@Neenu1995 
Seems the list is sorted from oldest to newest, and that using the sync-token we can get what has changed.

But, the sync-token doesn't say which were removed. Only a list of contacts is returned (modified/new).

Can you please offer to sort in the opposite direction (from new to old) ? This can help in case we've cached the results, and need only the newest ones (and don't have a valid sync-token).

In addition, for sync-token, please offer a way to detect which were removed, because this seems missing and can only be found if I query the entire list again.

**Comment by burkedavison** [comment]
Closing this issue as we are unable to provide adequate customer support through this forum. If you feel there is a bug or a feature request associated with this ticket, please open a new issue. Otherwise, https://cloud.google.com/support is best able to provide timely answers to API-specific questions.
