### ISSUE TITLE
Bug: setting `requestSyncToken` for `otherContacts.list()` doesn't give you back the `nextSyncToken`

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleapis/google-api-java-client-services#7999]
This happens when I try it:

https://developers.google.com/people/api/rest/v1/otherContacts/list?apix_params=%7B%22pageSize%22%3A1000%2C%22readMask%22%3A%22emailAddresses%2Cnames%2CphoneNumbers%22%2C%22requestSyncToken%22%3Atrue%7D

![image](https://user-images.githubusercontent.com/5357526/118113787-66e87c80-b3ef-11eb-8e7c-b49929984e10.png)

**Comment by AndroidDeveloperLB** [comment]
@Neenu1995 
It seems this occurs only for the first page. On the last page-query, I do get the sync token. 

So, if it's intended, it should be documented, and if it's not, it's a bug.

**Comment by lesv** [comment]
@danoscarmike Do we have a TW for the Workspace People api?  They should get this.

**Comment by danoscarmike** [comment]
@sqrrrl can you help us out here?

**Comment by sqrrrl** [comment]
I filed an internal bug (200949561). Our team doesn't currently work with People API, but forwarded the issue to the eng team since they maintain those docs.

**Comment by AndroidDeveloperLB** [comment]
@sqrrrl Thank you!

**Comment by lesv** [comment]
I'm going to close this since there isn't anything else that can be done here.

**Comment by AndroidDeveloperLB** [comment]
@lesv Was there any progress for this though? You guys said it was filed...

**Comment by lesv** [comment]
According to the internal issue, this is working-as-intented.  The sync token is only updated on the last page.  It's still open awaiting an acknowledgement. Once/if that happens, the docs should be updated.

**Comment by AndroidDeveloperLB** [comment]
@lesv It's not intuitive and not clear from the current documentation that it works this way. As long as there is no documentation about this, I think it should still be considered a bug.
