### ISSUE TITLE
Apigee API support

### ISSUE THREAD

**Issue by yangzii0920** [googleapis/google-api-java-client-services#8255]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do: 
**I'm trying to write a java app that interacts with Apigee, preferably with a java client.**
- What code you've already tried: 
**Found this repo when looking for Google client library for java. Searched in maven central for the apigee client and found nothing.**
- Any error messages you're getting: **Apigee V1 is listed in supported APIs in README but the [link](https://github.com/googleapis/google-api-java-client-services/blob/master/clients/google-api-services-apigee/v1) returns 404. Is the apigee java client no longer supported or moved to somewhere else?**

**Comment by meltsufin** [comment]
The Apigee API Client is here: https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-apigee/v1
