### ISSUE TITLE
My Business Information API java client not published

### ISSUE THREAD

**Issue by chroustradek** [googleapis/google-api-java-client-services#9270]
#### Environment details

  - Programming language: Java

#### Steps to reproduce

  1. Go to https://developers.google.com/my-business/preview/reference/businessinformation/rest page
  2. Read advice: _To call this service, we recommend that you use the Google-provided client libraries._
  3. But there is no java client of `My Business Information API` library

Only way is to generate custom library based on https://mybusinessbusinessinformation.googleapis.com/$discovery/rest?version=v1 with your generator: https://github.com/googleapis/google-api-java-client-services/tree/master/generator ... It is little tricky to find out how to get your `My Business Information API client` as java client.
 
#### Steps to fix
Release `My Business Information API java client`  to maven repo.

**Comment by lesv** [comment]
Please file an [issuetracker](https://issuetracker.google.com/) issue about this.
