### ISSUE TITLE
Use 'implementation' instead of 'compile' for dependenies in build.gradle files

### ISSUE THREAD

**Issue by ashutoshdubey133** [googleapis/google-api-java-client-services#9537]
'compile' has been removed from Gradle 7+ and instead 'implementation' should be used for the dependencies.

For example here- [https://github.com/googleapis/google-api-java-client-services/tree/master/clients/google-api-services-youtube/v3#gradle](https://github.com/googleapis/google-api-java-client-services/tree/master/clients/google-api-services-youtube/v3#gradle)

This would include changing the readme of all the api's Readme.

**Comment by lesv** [comment]
@danoscarmike This is a bunch of work and probably should be scheduled.

**Comment by lesv** [comment]
@chingor13 FYI
@danoscarmike FYI
@Neenu1995 FYI

**Comment by Neenu1995** [comment]
README is templated. Should be fixable in a PR.

**Comment by lesv** [comment]
Yep - agree.

**Comment by Neenu1995** [comment]
https://github.com/googleapis/google-api-java-client-services/pull/11811
